# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('text', models.TextField()),
                ('device', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
